#!/bin/bash

# This file is part of the Bodhi Linux Web Browser Manager.
#
# License: GPL-3.0 or later
#
# (c) Bodhi Linux Team (2022-2023)
# (c) Feren Team (2015-2020) <ferenosdev@outlook.com>
# (c) AZorin 2010-(2015) <azorin@zoringroup.com>
# (c) Zorink (2010) <zorink@zoringroup.com>

# shellcheck disable=SC2181

export TEXTDOMAIN="browser-manager"
export TEXTDOMAINDIR="/home/al/code/web-browser-manager/usr/share/locale"

# Check if program is installed
dpkg -l palemoon | grep -q ^ii

if [ $? -eq 0 ]; then
    if [ -e "/usr/bin/palemoon" ]; then
        zenity --info --title="$(gettext "Information")" --text="$(gettext "Palemoon is already installed")" --no-wrap &
        exit 0
    fi
fi

# Check for root
if [ ! "$(whoami)" = "root" ]; then
    zenity --question --title="$(gettext "Continue?")" --text "$(gettext "The use of Palemoon is governed by the Terms of Use and Privacy Policy found at:\n\n    <a href='https://www.palemoon.org/licensing.shtml'>https://www.palemoon.org/licensing.shtml</a>\n    <a href='https://www.palemoon.org/policies/privacy.shtml'>https://www.palemoon.org/policies/privacy.shtml</a>\n\nAre you sure you want to install Palemoon?")"

    if [ ! $? -eq 0 ]; then
        exit 0
    fi

    pkexec "$0"

    if [ $? -eq 127 ]; then
        exit 0
    fi

    # Double Check Package
    if [ -e "/usr/bin/palemoon" ]; then
        zenity --info --title="$(gettext "Installation Complete")" --text="$(gettext "Palemoon was successfully installed")" --no-wrap &
        exit 0
    fi
    # Error
    zenity  --error --text="$(gettext "Web Browser Manager couldn't install Palemoon successfully

A log can be found at File System/tmp/palemoon-install-log")" --title="$(gettext "Error")" --no-wrap &
    exit 0
fi

# Check if program is installed
dpkg -l palemoon | grep -q ^ii

if [ ! $? -eq 0 ]; then
    if [ ! -e "/usr/bin/palemoon" ]; then
        #Log output
        exec 1>/tmp/palemoon-install-log 2>&1
        # Install program
        apt-get update
        apt-get -y install palemoon
    fi
    exit 0
fi

# Error
zenity  --error --text="An error occured while initiating the Palemoon installation process" --title="$(gettext "Error")" --no-wrap &
exit 0
