#!/bin/bash

###############################
#Check if program is installed#
###############################
dpkg -l palemoon | grep -q ^ii

if [ $? -eq 0 ]; then
         if [ -e "/usr/bin/palemoon" ]; then
                  zenity --info --title="Information" --text="Palemoon is already installed" --no-wrap &
                  exit 0
         fi
fi



################
#Check for root#
################
if [ ! $(whoami) = "root" ]; then
    zenity --question --title="Continue?" --text "The use of Palemoon is governed by the Terms of Use and Privacy Policy found at:\n\n    <a href='https://www.palemoon.org/licensing.shtml'>https://www.palemoon.org/licensing.shtml</a>\n    <a href='https://www.palemoon.org/policies/privacy.shtml'>https://www.palemoon.org/policies/privacy.shtml</a>\n\nAre you sure you want to install Palemoon?"

    if [ ! $? -eq 0 ]; then
           exit
    fi

    pkexec "$0"
    
    if [ $? -eq 127 ]; then
        exit 0
    fi
    
    ######################
    #Double Check Package#
    ######################
    if [ -e "/usr/bin/palemoon" ]; then
            zenity --info --title="Installation Complete" --text="Palemoon was successfully installed" --no-wrap &
            exit 0
    fi
    #######
    #Error#
    #######
    zenity  --error --text="Web Browser Manager couldn't install Palemoon successfully

A log can be found at File System/tmp/palemoon-install-log" --title="Error" --no-wrap &
    exit 0
fi

###################################
#Check if program is not installed#
###################################
dpkg -l palemoon | grep -q ^ii

if [ ! $? -eq 0 ]; then
         if [ ! -e "/usr/bin/palemoon" ]; then

#################
#Install program#
#################
        #Log output
        exec 1>/tmp/palemoon-install-log 2>&1
        
                  apt-get update
                  apt-get -y install palemoon
         fi
         exit
fi

#######
#Error#
#######
zenity  --error --text="An error occured while initiating the Palemoon installation process" --title="Error" --no-wrap &
exit 0
