#!/bin/bash

# This file is part of the Bodhi Linux Web Browser Manager.
#
# License: GPL-3.0 or later
#
# (c) Bodhi Linux Team (2022-2023)
# (c) Feren Team (2015-2020) <ferenosdev@outlook.com>
# (c) AZorin 2010-(2015) <azorin@zoringroup.com>
# (c) Zorink (2010) <zorink@zoringroup.com>

# shellcheck disable=SC2181

# Check if program is installed
dpkg -l google-chrome-stable | grep -q ^ii

if [ $? -eq 0 ]; then
    if [ -e "/usr/bin/google-chrome" ]; then
        zenity --info --title="Information" --text="Google Chrome is already installed" --no-wrap &
        exit 0
    fi
fi

# Check for root
if [ ! "$(whoami)" = "root" ]; then
    zenity --question --title="Continue?" --title="Continue?" --text "The use of Chrome is goverened by the Terms of Use and Privacy Policy found at:\n\n    <a href='https://www.google.com/chrome/terms/'>https://www.google.com/chrome/terms/</a>\n    <a href='https://www.google.com/chrome/privacy/'>https://www.google.com/chrome/privacy/</a>\n\nAre you sure you want to install Chrome?"

    if [ ! $? -eq 0 ]; then
        exit 0
    fi

    pkexec "$0"

    if [ $? -eq 127 ]; then
        exit 0
    fi

    # Double Check Package
    if [ -e "/usr/bin/google-chrome" ]; then
        zenity --info --title="Installation Complete" --text="Google Chrome was successfully installed" --no-wrap &
        exit 0
    fi
    # Error
    zenity  --error --text="Web Browser Manager couldn't install Google Chrome successfully

A log can be found at File System/tmp/chrome-install-log" --title="Error" --no-wrap &
    exit 0
fi

# Check if program is installed
dpkg -l google-chrome-stable | grep -q ^ii

if [ ! $? -eq 0 ]; then
    if [ ! -e "/usr/bin/google-chrome" ]; then
        # Log output
        exec 1>/tmp/chrome-install-log 2>&1

        if [ ! -f /etc/apt/sources.list.d/google-chrome.list ]; then
            wget -qO - https://dl.google.com/linux/linux_signing_key.pub | sudo tee /usr/share/keyrings/chrome-archive-keyring.pub  2>&1 1>/dev/null
            if [ ! $? -eq 0 ]; then
                echo "Failed to download keyring" >/tmp/chrome-install-log 2>&1
                exit 1
            fi
            echo -e "deb [signed-by=/usr/share/keyrings/chrome-archive-keyring.pub, arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list  2>&1 1>/dev/null
        fi
        # Log output
        exec 1>/tmp/chrome-install-log 2>&1
        sleep 1
        # Install program
        apt-get update
        apt-get -y install google-chrome-stable
    fi
    exit 0
fi

# Error
zenity  --error --text="An error occured while initiating the Google Chrome installation process" --title="Error" --no-wrap &
exit 0
