#!/bin/bash

###################################
#Check if program is not installed#
###################################
dpkg -l firefox | grep -q ^ii

if [ ! $? -eq 0 ] && [ ! -f /usr/bin/firefox ]; then
    zenity --info --title="Information" --text="Mozilla Firefox is not installed" --no-wrap &
    exit 0
fi

################
#Check for root#
################
if [ ! "$(whoami)" = "root" ]; then
    zenity --question --title="Continue?" --text "Are you sure you want to remove Mozilla Firefox?" --no-wrap

    if [ ! $? -eq 0 ]; then
            exit
    fi
    
    pkexec "$0" $@
    
    if [ $? -eq 127 ]; then
        exit 0
    fi
    
    ######################
    #Double Check Package#
    ######################
    dpkg -l firefox | grep -q ^ii

    if [ ! $? -eq 0 ] && [ ! -f /usr/bin/firefox ]; then
        zenity --info --title="Uninstalled Mozilla Firefox" --text="Mozilla Firefox was successfully removed" --no-wrap &
        exit 0
            #######
            #Error#
            #######
    fi
    zenity  --error --text="Web Browser Manager couldn't remove Mozilla Firefox successfully

A log can be found at File System/tmp/firefox-removal-log" --title="Error" --no-wrap &
    exit 0
fi

###############################
#Check if program is installed#
###############################
dpkg -l firefox | grep -q ^ii

if [ $? -eq 0 ] || [ -f /usr/bin/firefox ]; then

###################
#Uninstall program#
###################
        #Log output
        exec 1>/tmp/firefox-removal-log 2>&1
        
            #Remove Firefox, PPA and keys
            apt-get -y purge firefox
            rm -f /etc/apt/sources.list.d/mozillateam-ubuntu-ppa-jammy.list
            rm -f /etc/apt/trusted.gpg.d/mozillateam-ubuntu-ppa*
        fi
        exit
fi

#######
#Error#
#######
zenity  --error --text="An error occured while initiating the Mozilla Firefox removal process" --title="Error" --no-wrap &
exit 0
