#!/bin/bash

# This file is part of the Bodhi Linux Web Browser Manager.
#
# License: GPL-3.0 or later
#
# (c) Bodhi Linux Team (2022-2023)
# (c) Feren Team (2015-2020) <ferenosdev@outlook.com>
# (c) AZorin 2010-(2015) <azorin@zoringroup.com>
# (c) Zorink (2010) <zorink@zoringroup.com>

# shellcheck disable=SC2181

# Check if program is installed
dpkg -l slimjet | grep -q ^ii

if [ $? -eq 0 ]; then
    if [ -e "/usr/bin/flashpeak-slimjet" ]; then
        zenity --info --title="Information" --text="Slimjet is already installed" --no-wrap &
        exit 0
    fi
fi

# Check for root
if [ ! "$(whoami)" = "root" ]; then
    zenity --question --title="Continue?" --text "The use of Slimjet is governed by the Terms of Use and Privacy Policy found at:\n\n    <a href='https://www.gnu.org/philosophy/philosophy.html'>https://www.gnu.org/philosophy/philosophy.html</a>\n    <a href='https://wiki.gnome.org/Apps/Web/PrivacyPolicy'>https://wiki.gnome.org/Apps/Web/PrivacyPolicy</a>\n\nAre you sure you want to install Slimjet?" --no-wrap

    if [ ! $? -eq 0 ]; then
        exit 0
    fi

    pkexec "$0"

    if [ $? -eq 127 ]; then
        exit 0
    fi

    # Double Check Package
    if [ -e "/usr/bin/flashpeak-slimjet" ]; then
        zenity --info --title="Installation Complete" --text="Slimjet was successfully installed" --no-wrap &
        exit 0
    fi
    # Error
    zenity  --error --text="Web Browser Manager couldn't install Slimjet successfully

A log can be found at File System/tmp/slimjet-install-log" --title="Error" --no-wrap &
    exit 0
fi

# Check if program is installed
dpkg -l slimjet | grep -q ^ii

if [ ! $? -eq 0 ]; then
    if [ ! -e "/usr/bin/flashpeak-slimjet" ]; then
        #Log output
        exec 1>/tmp/slimjet-install-log 2>&1
        # Install program
        apt-get update
        apt-get -y install slimjet
    fi
    exit 0
fi

# Error
zenity  --error --text="An error occured while initiating the Slimjet installation process" --title="Error" --no-wrap &
exit 0
