#!/bin/bash

# This file is part of the Bodhi Linux Web Browser Manager.
#
# License: GPL-3.0 or later
#
# (c) Bodhi Linux Team (2022-2023)
# (c) Feren Team (2015-2020) <ferenosdev@outlook.com>
# (c) AZorin 2010-(2015) <azorin@zoringroup.com>
# (c) Zorink (2010) <zorink@zoringroup.com>

# shellcheck disable=SC2181

# Check if program is installed
dpkg -l falkon | grep -q ^ii

if [ ! $? -eq 0 ]; then
    if [ ! -e "/usr/bin/falkon" ]; then
        zenity --info --title="Information" --text="Falkon is not installed" --no-wrap &
        exit 0
    fi
fi

# Check for root
if [ ! "$(whoami)" = "root" ]; then
    zenity --question --title="Continue?" --text "Are you sure you want to remove Falkon?" --no-wrap

    if [ ! $? -eq 0 ]; then
        exit 0
    fi

    pkexec "$0" $@

    if [ $? -eq 127 ]; then
        exit 0
    fi

    # Double Check Package
    dpkg -l falkon | grep -q ^ii

    if [ ! $? -eq 0 ]; then
        if [ ! -e "/usr/bin/falkon" ]; then
            zenity --info --title="Uninstalled Falkon" --text="Falkon was successfully removed" --no-wrap &
            exit 0
        fi
        # Error
        zenity  --error --text="Web Browser Manager couldn't remove Falkon successfully

        A log can be found at File System/tmp/falkon-removal-log" --title="Error" --no-wrap &
        exit 0
    fi
fi


# Check if program is installed
dpkg -l falkon | grep -q ^ii

if [ $? -eq 0 ]; then
    if [ -e "/usr/bin/falkon" ]; then
        # Log output
        exec 1>/tmp/falkon-removal-log 2>&1
        # Uninstall program
        apt-get -y purge falkon
        fi
    exit 0
fi

# Error
zenity  --error --text="An error occured while initiating the Falkon removal process" --title="Error" --no-wrap &
exit 0
