#!/bin/bash

# This file is part of the Bodhi Linux Web Browser Manager.
#
# License: GPL-3.0 or later
#
# (c) Bodhi Linux Team (2022-2023)
# (c) Feren Team (2015-2020) <ferenosdev@outlook.com>
# (c) AZorin 2010-(2015) <azorin@zoringroup.com>
# (c) Zorink (2010) <zorink@zoringroup.com>

# shellcheck disable=SC2181

export TEXTDOMAIN="browser-manager"
export TEXTDOMAINDIR="../../../share/locale"

# Check if program is installed
dpkg --get-selections | grep -P -q "opera-stable\t*install"

if [ ! $? -eq 0 ]; then
    if [ ! -e "/usr/bin/opera" ]; then
        zenity --info --title="$(gettext "Information")" --text="$(gettext "Opera is not installed")" --no-wrap &
        exit 0
    fi
fi

# Check for root
if [ ! "$(whoami)" = "root" ]; then
    zenity --question --title="$(gettext "Continue?")" --text "$(gettext "Are you sure you want to remove Opera?")" --no-wrap

    if [ ! $? -eq 0 ]; then
        exit 0
    fi

    pkexec "$0" $@

    if [ $? -eq 127 ]; then
        exit 0
    fi


    # Double Check Package
    dpkg --get-selections | grep -P -q "opera-stable\t*install"

    if [ ! $? -eq 0 ]; then
        if [ ! -e "/usr/bin/opera" ]; then
            zenity --info --title="$(gettext "Uninstalled Opera")" --text="$(gettext "Opera was successfully removed")" --no-wrap &
            exit 0
        fi
        # Error
        zenity  --error --text="$(gettext "Web Browser Manager couldn't remove Opera successfully

A log can be found at File System/tmp/opera-removal-log")" --title="$(gettext "Error")" --no-wrap &
        exit 0
    fi
fi


# Check if program is installed
dpkg --get-selections | grep -P -q "opera-stable\t*install"

if [ $? -eq 0 ]; then
    if [ -e "/usr/bin/opera" ]; then
        # Log output
        exec 1>/tmp/opera-removal-log 2>&1
        # Uninstall program
        apt-get -y purge opera-stable
        # Remove PPA
        rm -f /usr/share/keyrings/opera-archive-keyring.key
        rm -f /etc/apt/sources.list.d/opera-stable.list
    fi
    exit 0
fi

# Error
zenity  --error --text="$(gettext "An error occured while initiating the Opera removal process")" --title="$(gettext "Error")" --no-wrap &
exit 0
