#!/bin/bash

###############################
#Check if program is installed#
###############################
dpkg -l epiphany-browser | grep -q ^ii

if [ $? -eq 0 ]; then
         if [ -e "/usr/bin/epiphany-browser" ]; then
                  zenity --info --title="Information" --text="GNOME Web is already installed" --no-wrap &
                  exit 0
         fi
fi



################
#Check for root#
################
if [ ! $(whoami) = "root" ]; then
    zenity --question --title="Continue?" --text "The use of GNOME Web is governed by the Terms of Use and Privacy Policy found at:\n\n    <a href='https://www.gnu.org/philosophy/philosophy.html'>https://www.gnu.org/philosophy/philosophy.html</a>\n    <a href='https://wiki.gnome.org/Apps/Web/PrivacyPolicy'>https://wiki.gnome.org/Apps/Web/PrivacyPolicy</a>\n\nAre you sure you want to install GNOME Web?" --no-wrap
    
    if [ ! $? -eq 0 ]; then
           exit
    fi

    pkexec "$0"
    
    if [ $? -eq 127 ]; then
        exit 0
    fi
    
    ######################
    #Double Check Package#
    ######################
    if [ -e "/usr/bin/epiphany-browser" ]; then
            zenity --info --title="Installation Complete" --text="GNOME Web was successfully installed" --no-wrap &
            exit 0
    fi
    #######
    #Error#
    #######
    zenity  --error --text="Web Browser Manager couldn't install GNOME Web successfully

A log can be found at File System/tmp/epiphany-install-log" --title="Error" --no-wrap &
    exit 0
fi

###################################
#Check if program is not installed#
###################################
dpkg -l epiphany-browser | grep -q ^ii

if [ ! $? -eq 0 ]; then
         if [ ! -e "/usr/bin/epiphany-browser" ]; then

#################
#Install program#
#################
        #Log output
        exec 1>/tmp/epiphany-install-log 2>&1
        
                  apt-get update
                  apt-get -y install --no-install-recommends epiphany-browser
         fi
         exit
fi

#######
#Error#
#######
zenity  --error --text="An error occured while initiating the GNOME Web installation process" --title="Error" --no-wrap &
exit 0
