#!/bin/bash

# This file is part of the Bodhi Linux Web Browser Manager.
#
# License: GPL-3.0 or later
#
# (c) Bodhi Linux Team (2022-2023)
# (c) Feren Team (2015-2020) <ferenosdev@outlook.com>
# (c) AZorin 2010-(2015) <azorin@zoringroup.com>
# (c) Zorink (2010) <zorink@zoringroup.com>

# shellcheck disable=SC2181

export TEXTDOMAIN="browser-manager"
export TEXTDOMAINDIR="/home/al/code/web-browser-manager/usr/share/locale"

# Check if program is installed

dpkg -l brave-browser | grep -q ^ii

if [ $? -eq 0 ]; then
    if [ -e "/usr/bin/brave-browser" ]; then
        zenity --info --title="$(gettext "Information")" --text="$(gettext "Brave is already installed")" --no-wrap &
        exit 0
    fi
fi

# Check for root
if [ ! "$(whoami)" = "root" ]; then
    zenity --question --title="$(gettext "Continue?")" --text "$(gettext "The use of Brave is governed by the Terms of Use and Privacy Policy found at:\n\n    <a href='https://brave.com/terms-of-use/'>https://brave.com/terms-of-use/</a>\n    <a href='https://brave.com/privacy/browser/'>https://brave.com/privacy/browser/</a>\n\nAre you sure you want to install Brave?")"

    if [ ! $? -eq 0 ]; then
        exit 0
    fi

    pkexec "$0"

    if [ $? -eq 127 ]; then
        exit 0
    fi

    # Double Check Package
    if [ -e "/usr/bin/brave-browser" ]; then
        zenity --info --title="$(gettext "Installation Complete")" --text="$(gettext "Brave was successfully installed")" --no-wrap &
        exit 0
    fi

    # Error
    zenity  --error --text="$(gettext "Web Browser Manager couldn't install Brave successfully

A log can be found at File System/tmp/brave-install-log")" --title="$(gettext "Error")" --no-wrap &
    exit 0
fi

# Remove Old Brave
dpkg -l brave-browser | grep -q ^ii

if [ $? -eq 0 ]; then
    if [ -e "/usr/bin/brave-browser" ]; then
        apt-get -y purge brave-browser
        rm -f /etc/apt/sources.list.d/brave.list
    fi
fi

# Check if program is installed
dpkg -l brave-browser | grep -q ^ii

if [ ! $? -eq 0 ]; then

    if [ ! -e "/usr/bin/brave-browser" ]; then
        # Add PPA if it doesn't exist
        if [ ! -f /etc/apt/sources.list.d/brave.list ]; then
            wget -qO - https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg | sudo tee /usr/share/keyrings/brave-browser-archive-keyring.gpg 2>&1 1>/dev/null
            if [ ! $? -eq 0 ]; then
                echo "$(gettext "Failed to download keyring")" >/tmp/brave-install-log 2>&1
                exit 1
            fi
            echo "$(gettext "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg, arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main")" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list 2>&1 1>/dev/null
        fi
        # Log output
        exec 1>/tmp/brave-install-log 2>&1
        sleep 1
        # Install program
        apt-get update
        apt-get -y install brave-browser
    fi
    exit
fi

# Error
zenity  --error --text="$(gettext "An error occured while initiating the Brave installation process")" --title="$(gettext "Error")" --no-wrap &
exit 0
