#!/bin/bash

# This file is part of the Bodhi Linux Web Browser Manager.
#
# License: GPL-3.0 or later
#
# (c) Bodhi Linux Team (2022-2023)
# (c) Feren Team (2015-2020) <ferenosdev@outlook.com>
# (c) AZorin 2010-(2015) <azorin@zoringroup.com>
# (c) Zorink (2010) <zorink@zoringroup.com>

# shellcheck disable=SC2181

# Check if program is installed
dpkg -l brave-browser | grep -q ^ii

if [ $? -eq 0 ]; then
    if [ -e "/usr/bin/brave-browser" ]; then
        zenity --info --title="Information" --text="Brave is already installed" --no-wrap &
        exit 0
    fi
fi

# Check for root
if [ ! "$(whoami)" = "root" ]; then
    zenity --question --title="Continue?" --text "The use of Brave is governed by the Terms of Use and Privacy Policy found at:\n\n    <a href='https://brave.com/terms-of-use/'>https://brave.com/terms-of-use/</a>\n    <a href='https://brave.com/privacy/browser/'>https://brave.com/privacy/browser/</a>\n\nAre you sure you want to install Brave?"

    if [ ! $? -eq 0 ]; then
        exit 0
    fi

    pkexec "$0"

    if [ $? -eq 127 ]; then
        exit 0
    fi

    # Double Check Package
    if [ -e "/usr/bin/brave-browser" ]; then
        zenity --info --title="Installation Complete" --text="Brave was successfully installed" --no-wrap &
        exit 0
    fi

    # Error
    zenity  --error --text="Web Browser Manager couldn't install Brave successfully

A log can be found at File System/tmp/brave-install-log" --title="Error" --no-wrap &
    exit 0
fi

# Remove Old Brave
dpkg -l brave-browser | grep -q ^ii

if [ $? -eq 0 ]; then
    if [ -e "/usr/bin/brave-browser" ]; then
        apt-get -y purge brave-browser
        rm -f /etc/apt/sources.list.d/brave.list
    fi
fi

# Check if program is installed
dpkg -l brave-browser | grep -q ^ii

if [ ! $? -eq 0 ]; then

    if [ ! -e "/usr/bin/brave-browser" ]; then
        # Log output
        exec 1>/tmp/brave-install-log 2>&1

        # Add PPA if it doesn't exist
        if [ ! -f /etc/apt/sources.list.d/brave.list ]; then
            curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
            if [ ! $? -eq 0 ]; then
                exit 1
            fi
            echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg, arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
        fi
        sleep 1
        # Install program
        apt-get update
        apt-get -y install brave-browser
    fi
    exit
fi

# Error
zenity  --error --text="An error occured while initiating the Brave installation process" --title="Error" --no-wrap &
exit 0
