#!/bin/bash

# This file is part of the Bodhi Linux Web Browser Manager.
#
# License: GPL-3.0 or later
#
# (c) Bodhi Linux Team (2022-2023)
# (c) Feren Team (2015-2020) <ferenosdev@outlook.com>
# (c) AZorin 2010-(2015) <azorin@zoringroup.com>
# (c) Zorink (2010) <zorink@zoringroup.com>

# shellcheck disable=SC2181

# Check if program is installed
dpkg -l vivaldi-stable | grep -qs ^ii

if [ $? -eq 0 ]; then
    if [ -e "/usr/bin/vivaldi" ]; then
        zenity --info --title="Information" --text="Vivaldi is already installed" --no-wrap &
        exit 0
    fi
fi

# Check for root
if [ ! "$(whoami)" = "root" ]; then
    zenity --question --title="Continue?" --text "The usage of Vivaldi is governed by the Vivaldi EULA and Privacy Policy found at:\n\n    <a href='https://vivaldi.com/privacy/vivaldi-end-user-license-agreement/'>https://vivaldi.com/privacy/vivaldi-end-user-license-agreement/</a>\n    <a href='https://vivaldi.com/privacy/browser/'>https://vivaldi.com/privacy/browser/</a>\n\nAre you sure you want to install Vivaldi?"

    if [ ! $? -eq 0 ]; then
        exit 0
    fi

    pkexec "$0"

    if [ $? -eq 127 ]; then
        exit 0
    fi

    # Double Check Package
    if [ -e "/usr/bin/vivaldi" ]; then
        zenity --info --title="Installation Complete" --text="Vivaldi was successfully installed" --no-wrap &
        exit 0
    fi
    # Error
    zenity  --error --text="Web Browser Manager couldn't install Vivaldi successfully

A log can be found at File System/tmp/vivaldi-install-log" --title="Error" --no-wrap &
    exit 0
fi

# Check if program is installed
dpkg -l vivaldi-stable | grep -qs ^ii

if [ ! $? -eq 0 ]; then
    if [ ! -e "/usr/bin/vivaldi" ]; then
        # Log output
        exec 1>/tmp/vivaldi-install-log 2>&1
        # Add PPA if it doesn't exist
        if [ ! -f /etc/apt/sources.list.d/vivaldi.list ]; then
            wget -qO - http://repo.vivaldi.com/stable/linux_signing_key.pub | sudo tee /usr/share/keyrings/vivaldi-archive-keyring.pub
            if [ ! $? -eq 0 ]; then
                exit 1
            fi
            echo "deb [signed-by=/usr/share/keyrings/vivaldi-archive-keyring.pub, arch=amd64] http://repo.vivaldi.com/stable/deb/ stable main" | sudo tee /etc/apt/sources.list.d/vivaldi.list
        fi
        sleep 1
        # Install program
        apt-get update
        apt-get -y install vivaldi-stable
    fi
    exit 0
fi

# Error
zenity  --error --text="An error occured while initiating the Vivaldi installation process" --title="Error" --no-wrap &
exit 0
