#!/bin/bash

# This file is part of the Bodhi Linux Web Browser Manager.
#
# License: GPL-3.0 or later
#
# (c) Bodhi Linux Team (2022-2023)
# (c) Feren Team (2015-2020) <ferenosdev@outlook.com>
# (c) AZorin 2010-(2015) <azorin@zoringroup.com>
# (c) Zorink (2010) <zorink@zoringroup.com>

# shellcheck disable=SC2181

export TEXTDOMAIN="browser-manager"
export TEXTDOMAINDIR="/home/al/code/web-browser-manager/usr/share/locale"

# Check if program is installed
dpkg -l vivaldi-stable | grep -q ^ii

if [ ! $? -eq 0 ]; then
    if [ ! -e "/usr/bin/vivaldi" ]; then
        zenity --info --title="$(gettext "Information")" --text="$(gettext "Vivaldi is not installed")" --no-wrap &
        exit 0
    fi
fi

# Check for root
if [ ! "$(whoami)" = "root" ]; then
    zenity --question --title="$(gettext "Continue?")" --text "$(gettext "Are you sure you want to remove Vivaldi?")" --no-wrap

    if [ ! $? -eq 0 ]; then
        exit 0
    fi

    pkexec "$0" $@

    if [ $? -eq 127 ]; then
        exit 0
    fi

    # Double Check Package
    dpkg -l vivaldi-stable | grep -q ^ii

    if [ ! $? -eq 0 ]; then
        if [ ! -e "/usr/bin/vivaldi" ]; then
            zenity --info --title="$(gettext "Uninstalled Vivaldi")" --text="$(gettext "Vivaldi was successfully removed")" --no-wrap &
            exit 0
        fi
        # Error
        zenity  --error --text="$(gettext "Web Browser Manager couldn't remove Vivaldi successfully

A log can be found at File System/tmp/vivaldi-removal-log")" --title="$(gettext "Error")" --no-wrap
        exit 0
    fi
fi

# Check if program is installed
dpkg -l vivaldi-stable | grep -q ^ii

if [ $? -eq 0 ]; then
    if [ -e "/usr/bin/vivaldi" ]; then
        # Log output
        exec 1>/tmp/vivaldi-removal-log 2>&1
        # Uninstall program
        apt-get -y purge vivaldi-stable
        # Remove PPA
        rm -f /usr/share/keyrings/vivaldi-archive-keyring.pub
        rm -f /etc/apt/sources.list.d/vivaldi.list
    fi
    exit 0
fi

# Error
zenity  --error --text="$(gettext "An error occured while initiating the Vivaldi removal process")" --title="$(gettext "Error")" --no-wrap &
exit 0
